### ISSUE TITLE
Compatibility with PHPCas 1.3.x

### ISSUE THREAD

**Issue by 3rwww1** [dfwarden/Roundcube-CAS-Authn#6]
The setPGTStorageFile() call issued in cas_init() uses a deprecated signature.

The _format_ argument was removed in 1.3, now it should only take a _path_ argument.
- see commit SHA  jasig/phpCAS@a0ab15965c4fdb8a247fad5553cce4d0152e6db3
- see issue jasig/phpCAS#15

**Comment by dfwarden** [comment]
Sorry this took so long, we have migrated from Roundcube to Google Mail at work so I haven't touched Roundcube in a long time.

I've updated the Readme to indicate everyone should use phpCAS 1.3.x.
