### ISSUE TITLE
phpCAS error: phpCAS::setPGTStorageFile(): an absolute path is needed for PGT storage to file

### ISSUE THREAD

**Issue by thangnguyennang** [dfwarden/Roundcube-CAS-Authn#7]
Hi dfwarden,

We had the following issue when using CAS Proxy with pam_cas module:

When accessing the URL "https://<cas-server-hostname>/webmail/?_action=caslogin, we see an error:
"phpCAS error: phpCAS::setPGTStorageFile(): an absolute path is needed for PGT storage to file in <path-to-plugin>/cas_authn.php on line 326"

We used the default setting "$rcmail_config['cas_pgt_dir'] = '/tmp';".

Any suggestions for us? Thanks in advance.
### Our testing environment
- OS CentOS 6.4
- Roundcube 0.8.7
- phpCAS 1.3.2
- pam_cas Pam_cas-2.0.11-esup-2.0.5.tar.gz
- Cyrus 2.3.16
- No error logs of phpCAS (debug mode)

**Comment by dfwarden** [comment]
I'm sorry you're having trouble with this. I'm trying to get this plugin
working again in my spare time - we stopped hosting our own webmail product
and as a result I have been bad at keeping the plugin up to date.

It looks like you're hitting a problem that other people have mentioned
with the way phpCAS has changed the function signature of
setPGTStorageFile(). Older versions (I believe EPEL uses the older version
last time I checked) took 2 arguments - a string to indicate the format to
store PGTs and a string for the path. The new version (I believe) just
takes 1 string argument - the path. I have a feeling you have the new
version and it's not putting $rcmail_config['cas_pgt_dir'] in the right
argument position. I'd recommend checking the phpCAS docs for your version
of the setPGTStorageFile function and changing the source to match your
version.

Again, sorry that you're having trouble with this. I will try to block off
some time this weekend to try to get this issue sorted in my repo so other
people don't have this problem.

**Comment by thangnguyennang** [comment]
The issue is resolved when downgrading phpCAS version to 1.2.2. Thanks for your help.

**Comment by guidtz** [comment]
Hello, 
  i have the same problem with roundcube 1.0 and phpcas 1.3.2. 
In cas_authn.phpline 326 change 
phpCAS::setPGTStorageFile('xml', $cfg['cas_pgt_dir']);
to 
phpCAS::setPGTStorageFile($cfg['cas_pgt_dir']);

**Comment by dfwarden** [comment]
Sorry this took so long, we have migrated from Roundcube to Google Mail at work so I haven't touched Roundcube in a long time. This should be fixed in Master.

I've updated the Readme to indicate everyone should use phpCAS 1.3.x.
